const ENVIRONMENT = 'PRO'

const MINIMUM_SELL_VOLUME_USD = 1000

const DX_CONTRACT_ADDRESS = null

const MARKETS = [
  {tokenA: 'ETH', tokenB: 'RDN'},
  {tokenA: 'ETH', tokenB: 'OMG'}
]
const RDN_TOKEN_ADDRESS = null
const OMG_TOKEN_ADDRESS = null

const ETHEREUM_RPC_URL = ''
const BOT_ACCOUNT_MNEMONIC = null

module.exports = {
  ENVIRONMENT,
  MINIMUM_SELL_VOLUME_USD,
  DX_CONTRACT_ADDRESS,
  MARKETS,

  // CONTRACTS
  RDN_TOKEN_ADDRESS,
  OMG_TOKEN_ADDRESS,

  // Ethereum config
  ETHEREUM_RPC_URL,
  BOT_ACCOUNT_MNEMONIC
}
